#!/usr/bin/bash

pxe(){


it=`ip a | grep -E "state (UP|DOWN)" | awk -F ": " '{ print $2 }' | head -n 2 | tail -n 1`

cat >> /etc/sysconfig/network-scripts/ifcfg-$it << EOF
# Generated by parse-kickstart
TYPE=Ethernet
DEVICE=$it
ONBOOT=yes
BOOTPROTO=static
IPV6INIT=no
PROXY_METHOD=none
BROWSER_ONLY=no
IPV4_FAILURE_FATAL=no
IPV6_AUTOCONF=no
IPV6_DEFROUTE=no
IPV6_FAILURE_FATAL=no
NAME="System $it"
IPADDR=192.168.0.1
NETMASK=255.255.255.0
EOF

dnf install dnsmasq -y
mv /etc/dnsmasq.conf  /etc/dnsmasq.conf.backup

cat >> /etc/dnsmasq.conf << EOF
interface=$it,lo
#bind-interfaces
domain=SERVEUR.PXE.esgi.local
# DHCP range-leases
dhcp-range= $it,192.168.0.3,192.168.0.253,255.255.255.0,1h
# PXE
dhcp-boot=pxelinux.0,pxeserver,192.168.0.1
# Gateway
#dhcp-option=3,192.168.0.255
# DNS
#dhcp-option=6,192.168.0.1, 8.8.8.8
server=8.8.4.4
# Broadcast Address
#dhcp-option=28,192.168.0.255
# NTP Server
dhcp-option=42,0.0.0.0
pxe-prompt="Press F8 for menu.", 60
pxe-service=x86PC, "Install CentOS 8 from network server 192.168.0.1", pxelinux
enable-tftp
tftp-root=/var/lib/tftpboot
EOF

dnf install syslinux -y
dnf install tftp-server -y
cp -r /usr/share/syslinux/* /var/lib/tftpboot
mkdir /var/lib/tftpboot/pxelinux.cfg
touch /var/lib/tftpboot/pxelinux.cfg/default

cat >> /var/lib/tftpboot/pxelinux.cfg/default << EOF
default menu.c32
prompt 0
timeout 300
ONTIMEOUT local

menu title ########## PXE Boot Menu ##########

label 1
menu label ^1) Install Rocky Linux 8 x64 
kernel rocky8/vmlinuz
append initrd=rocky8/initrd.img method=ftp://192.168.0.1/pub/data/rocky8/ devfs=nomount ip=dhcp

label 2
menu label ^2) Install Rocky Linux 8 AUTO ON
kernel rocky8/vmlinuz
append initrd=rocky8/initrd.img method=ftp://192.168.0.1/pub/data/rocky8/ devfs=nomount ip=dhcp ramdisk=32768 inst.ks=ftp://192.168.0.1/pub/data/rocky8/ks.cfg

EOF

#wget https://download.rockylinux.org/pub/rocky/8/isos/x86_64/Rocky-8.4-x86_64-dvd1.iso -O /data/rocky8.iso
# 
mount /dev/sr0 /mnt
mkdir /var/lib/tftpboot/rocky8
cp /mnt/images/pxeboot/vmlinuz /var/lib/tftpboot/rocky8
cp /mnt/images/pxeboot/initrd.img /var/lib/tftpboot/rocky8
chmod 755 -R /var/lib/tftpboot/rocky8

##snapchot iso

mkdir -p /data/rocky8/AppStream


cat >> /data/rocky8/ks.cfg << EOF
# Set the authentication options for the system
# auth --passalgo=sha512 --useshadow
# Install OS instead of upgrade
# install
graphical
# License agreement
eula --agreed
# Use network installation
# cdrom
#repo --name="AppStream" --baseurl="ftp://192.168.0.1/pub/data/rocky8/"

url --url="ftp://192.168.0.1/pub/data/rocky8/BaseOS/"

# Use text mode install
text
# Disable Initial Setup on first boot
firstboot --disable
# Keyboard layout
keyboard --vckeymap=fr --xlayouts='fr'
# System language
lang en_US.UTF-8
# Network information
network --onboot=yes --bootproto=dhcp --device=link --activate --nameserver=1.0.0.1,1.1.1.1
## --noipv6
# Root password
rootpw V@grant1

firewall --enabled --ssh --http --dns --https
#--service=ssh

# SELinux configuration
#selinux --enforcing
selinux --permissive
# Do not configure the X Window System
skipx
# System timezone
timezone Europe/Paris --isUtc
# Add a user named packer
# user --name=vagrant --groups=wheel --password=V@grant1 --plaintext

# # System bootloader configuration
# bootloader --location=mbr --append="crashkernel=auto"
# # Clear the Master Boot Record
# zerombr
# # Remove partitions
# clearpart --all --initlabel
# # Automatically create partitions using LVM
# # autopart --type=lvm

zerombr
clearpart --all --initlabel
#part /boot --fstype="xfs" --size=1024
#part pv.0 --fstype="lvmpv" --size=1 --grow
#volgroup VGROOT pv.0
#logvol swap --fstype="swap" --size=500 --name=swap --vgname=VGROOT
#logvol / --fstype="xfs" --size=5120 --name=root --vgname=VGROOT

part raid.sda0 --fstype="mdmember" --ondisk=sda --size=1025
part raid.sbd0 --fstype="mdmember" --ondisk=sdb --size=1025
part raid.sda1 --fstype="mdmember" --ondisk=sda --size=1 --grow
part raid.sdb1 --fstype="mdmember" --ondisk=sdb --size=1 --grow

raid /boot --device=boot --fstype="xfs" --level=RAID1 --label=BOOT raid.sda0 raid.sdb0
raid pv.00 --device=pv00 --fstype="lvmpv" --level=RAID1 --encrypted --passphrase="Ertyuiop" --luks-version=luks2 raid.sda1 raid.sdb1

volgroup VGCRYPT pv.00

logvol / --fstype="xfs" --size=6144 --label="RACINE" --name=root --vgname=VGCRYPT
logvol /tmp --fstype="ext4" --size=1024 --label="TMP" --name=tmp --vgname=VGCRYPT
logvol /var --fstype="xfs" --size=10240 --label="VAR" --name=var --vgname=VGCRYT
logvol /home --fstype="xfs" --size=1024 --label="HOME" --name=home --vgname=VGCRYPT
logvol swap --fstype="swap" --size=512 --label="SWAP" --name=swap --vgname=VGCRYPT


# Reboot after successful installation
reboot



# Reboot after successful installation
reboot

%packages --ignoremissing
# dnf group info minimal-environment
@^minimal-environment
wget
vim
%end

%post --log=/var/log/kickstart_post.log

mkdir /tmp/install_scripts

wget -r ftp://anonymous:@192.168.0.1/pub/data/rocky8/install_scripts -O /tmp/install_scripts
chmod +x /tmp/install_scripts
/tmp/install_scripts/main.sh 2>/var/log/install_script.err.log | tee /var/log/install_script.log

%end

EOF

cp -R /mnt/AppStream/* /data/rocky8/AppStream/

### Get script
# cp $(readlink -f $0) /data/rocky8/harden.sh
# sed -iE "s/^(.*# function.*)$//g" /data/rocky8/harden.sh
sudo dnf install yum-utils -y
var="lynx lynis epel-release glances htop mlocate"

for app in $var; do 
    echo $app
    download_rpm $app /data/rocky8/AppStream/Packages 
done

mkdir /data/rocky8/install_scripts
cp -r "$(pwd)" /data/rocky8/install_scripts

chmod -R 775 /data
umount /mnt

dnf install vsftpd -y
mkdir /var/ftp/pub/data

grep " /data " /etc/fstab | sed "s|/data|/var/ftp/pub/data|g" >> /etc/fstab
mount -a

sed -i '/anonymous_enable/s/NO/YES/' /etc/vsftpd/vsftpd.conf

chmod -R 755 /var/ftp/pub


systemctl restart dnsmasq
#systemctl status dnsmasq
systemctl restart vsftpd
#systemctl status vsftpd
systemctl enable dnsmasq
systemctl enable vsftpd

}